### ISSUE TITLE
Error en el logueo  

### ISSUE THREAD

**Issue by bruno512** [mescalitog/xTangoFacturas#1]
Buenas, me sale el siguiente error al querer loguearme con credenciales solicitadas.

![image](https://user-images.githubusercontent.com/32842115/43488520-74832b7c-94f0-11e8-822b-e8793d52659e.png)

**Comment by mescalitog** [comment]
Hola @bruno512 es posible que tengas un problema en la registracion de los objetos xtango.
Proba volviendo a registrarlos desde el administrador
![image](https://user-images.githubusercontent.com/10231443/43519766-11f723a6-9567-11e8-8f48-dbf3e91e3cda.png)

**Comment by bruno512** [comment]
![image](https://user-images.githubusercontent.com/32842115/43610656-1d7f4de0-967d-11e8-8054-529aba53e901.png)


Hola! Me dicen que los objetos ya se encuentran registrados al hacer clic donde me indicas, y el error sigue saliendo al loguearme.

**Comment by bruno512** [comment]
Hola! te cuento lo logre resolver este problema, pero me sale otro ahora ya no es una excepción sino que es un problema de permisos al parecer.

![image](https://user-images.githubusercontent.com/32842115/43663433-d4faa8a8-973f-11e8-99e9-f74417efcf37.png)

Con las mismas credenciales que intento loguearme aquí lo hago en el sistema tango de escritorio y logro entrar sin problemas, ya he revisado y re-revisado que los datos que le llegan a la función LogServerUserEx y son los correctos. Estaré olvidando configurar algo?

**Comment by mescalitog** [comment]
Genial @bruno512, me alegro que lo hayas logrado. En el campo de empresa tenes que poner el nombre de la empresa como aparece en el administrador de Tango, no como aparece en la base de datos. Normalmente esos dos nombres difieren. Ese mensaje de error viene de la funcion _LogServerUserEx_ es decir que lo devuelve _Tango_

**Comment by bruno512** [comment]
Gracias @mescalitog ! Te hago una consulta, tendrás ejemplos como estos pero para Recibos? Te felicito por el trabajo, me ayudo a entender y aprender un poco mejor xTango

**Comment by mescalitog** [comment]
Genial que te haya servido @bruno512.
No tengo hecho un ejemplo con Recibos, pero revisa la documentacion de xtango para ver cual es el proceso para recibos y despues modificá este código para crear recibos, va a ser muy parecido, aunque con otras estructuras.
